{{- range .Values.applications }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .appName }}
  namespace: {{ .namespace }}
spec:
  ingressClassName: {{ .ingressClass }}
  rules:
  - host: {{ .hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .backendService }}
            port:
              number: {{ .backendPort }}
        path: /
        pathType: Prefix
  {{- if .tlsEnabled }}
  tls:
  - hosts:
    - {{ .hostname }}
    secretName: {{ .tls.secretName }}
  {{- end }}
---
{{- end }}
{{- end }}
